version: '3'
services:
  ha-recorder-db-editor:
    build: 
      context: .
    restart: unless-stopped
    ports:
      - "2233:2233"
    volumes:
      - ./options.json:/data/options.json:ro
      - ${PWD}:/config
